### ISSUE TITLE
[bug] Cant update to v1.0.20

### ISSUE THREAD

**Issue by Coha05** [0xPellNetwork/network-config#18]
I've run the upgrade command

Got this error:

`root@ubuntu:~# ./pellcored-v1.0.20-linux-amd64 version
./pellcored-v1.0.20-linux-amd64: error while loading shared libraries: libwasmvm.x86_64.so: cannot open shared object file: No such file or directory
`

Same as on `cosmovisor/upgrade/bin/pellcored` check version

**Comment by jacksoom** [comment]
Thx for your issue. can u provide little more information about your server or docker ? It seems work fine on my server

**Comment by Coha05** [comment]
Here my info:
`Ubuntu 22.04`
`docker --version
Docker version 27.4.0, build bde2b89`

**Comment by jacksoom** [comment]
You probably didn't start it with our official image, so you do need to download libwasm lib. I'll provide an available script later to complete the dependency download.

**Comment by Coha05** [comment]
I access your docker with token login, yeah but still wait you update the upgrade.sh script. Have a nice day and hope the chain recover soon.

**Comment by Coha05** [comment]
Let pull the update after I installed `libwasmvm.x86_64.so`, it works well.
